### PR TITLE
#174 fix importing from packages in monorepos that need mutliple levels of node module directories

### LINKED ISSUE #174: bug: package importer fails in a monorepo like yarn workspaces
I've noticed that the package importer fails in monorepos that nest their node_modules folders and rely on module resolution to find the packages.

I've identified the source of the bug and will open a PR shortly to fix it

### PR DESCRIPTION
**Pull request by bdwain**
fix #174.

### CODE REVIEW

**Comment by maoberlehner** [comment]
Hey @bdwain, thank you for your contribution. CI is failing though – I've restarted the build to see if maybe something was temporary wrong with Travis (because it was a strange error) – but if it keeps failing, please take a look at why it is happening. Thank you very much!

**Comment by bdwain** [comment]
Hi @maoberlehner this same issue happened for me on master. I can look but I’m not sure what was causing it.

**Comment by maoberlehner** [comment]
Just triggered a CI run with the master branch (https://travis-ci.org/maoberlehner/node-sass-magic-importer/builds/402112995).

Please try to change the following line:

```diff
- const packagePath = path.dirname(findupSync(packageSearchPath));
+ const packagePath = path.dirname(findupSync(packageSearchPath, { cwd: options.cwd }));
```

**Comment by bdwain** [comment]
@maoberlehner it seems to have just hung when trying to build on node 8, but the others were fine

**Comment by maoberlehner** [comment]
@bdwain thanks, I just restarted the CI build and it passed.

I'll take a closer look at this and most likely will merge it at on the weekend. Thanks for contributing!

**Comment by bdwain** [comment]
cool! thanks!

**Comment by maoberlehner** [comment]
The branch was merged locally and a new tag (5.2.0) was published to npm. Thank you very much for contributing!

**Comment by bdwain** [comment]
Awesome! Thanks for responding so quickly!

**Pull request closed without merging**
